### ISSUE TITLE
Add support Heroku

### ISSUE THREAD

**Issue by kamileecher** [fertkir/tg-torrent-bot#13]
bro can you add support for heroku

**Comment by fertkir** [comment]
Hi, I've never used it... Do you want the bot to deploy to Heroku? Do you have any samples of what you want?

**Comment by kamileecher** [comment]
https://github.com/anasty17/mirror-leech-telegram-bot

Exp this

**Comment by fertkir** [comment]
As far as I understand, I just need to `apt install tg-torrent-bot` in Dockerfile, like here:
https://github.com/anasty17/mirror-leech-telegram-bot/blob/heroku/Dockerfile

Okay, if that's what you want, why not.

**Comment by kamileecher** [comment]
https://github.com/anasty17/mirror-leech-telegram-bot/tree/master/.github/workflows

https://github.com/anasty17/mirror-leech-telegram-bot/blob/master/Dockerfile

https://github.com/anasty17/mirror-leech-telegram-bot/blob/master/heroku.yml


https://dashboard.heroku.com/apps

**Comment by kamileecher** [comment]
These are the requirements to be able to run Heroku

**Comment by fertkir** [comment]
I see. Sure, I can add these files.
But how are you going to use the bot on Heroku? There's no much use of saving .torrent files to docker container... Do you need to get magnet-links only?

**Comment by kamileecher** [comment]
Let me give you an example, you can do it in the form of a command

For example, the Torrent Bittorrent client may have a telegram download feature.  or aria2c

Heroku will run the bot, but this will happen in telegram.  bot telegram can be added command to support both magnet and torrent file

**Comment by kamileecher** [comment]
If you install anasty bot you can understand the integration between Heroku and telegram.

**Comment by fertkir** [comment]
I've added deployment to heroku, check:
https://github.com/fertkir/tg-torrent-bot/blob/main/Dockerfile
https://github.com/fertkir/tg-torrent-bot/blob/main/.github/workflows/heroku-deploy.yml

**Comment by kamileecher** [comment]
2022-05-06T04:49:58.446290+00:00 heroku[worker.1]: State changed from starting to up
2022-05-06T04:49:59.235766+00:00 app[worker.1]: Fri, 06 May 2022 04:49:59 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
2022-05-06T04:49:59.235783+00:00 app[worker.1]: In the future, you will have to enable it yourself.
2022-05-06T04:49:59.235783+00:00 app[worker.1]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:999:30
2022-05-06T04:49:59.951594+00:00 app[worker.1]: events.js:291
2022-05-06T04:49:59.951603+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
2022-05-06T04:49:59.951604+00:00 app[worker.1]:       ^
2022-05-06T04:49:59.951604+00:00 app[worker.1]: 
2022-05-06T04:49:59.951605+00:00 app[worker.1]: Error: ENOENT: no such file or directory, open 'undefined/6154419.torrent'
2022-05-06T04:49:59.951605+00:00 app[worker.1]: Emitted 'error' event on WriteStream instance at:
2022-05-06T04:49:59.951606+00:00 app[worker.1]:     at errorOrDestroy (internal/streams/destroy.js:108:12)
2022-05-06T04:49:59.951606+00:00 app[worker.1]:     at WriteStream.onerror (_stream_readable.js:754:7)
2022-05-06T04:49:59.951606+00:00 app[worker.1]:     at WriteStream.emit (events.js:314:20)
2022-05-06T04:49:59.951606+00:00 app[worker.1]:     at internal/fs/streams.js:361:12
2022-05-06T04:49:59.951607+00:00 app[worker.1]:     at FSReqCallback.oncomplete (fs.js:156:23) {
2022-05-06T04:49:59.951607+00:00 app[worker.1]:   errno: -2,
2022-05-06T04:49:59.951608+00:00 app[worker.1]:   code: 'ENOENT',
2022-05-06T04:49:59.951608+00:00 app[worker.1]:   syscall: 'open',
2022-05-06T04:49:59.951608+00:00 app[worker.1]:   path: 'undefined/6154419.torrent'
2022-05-06T04:49:59.951608+00:00 app[worker.1]: }

**Comment by kamileecher** [comment]
![Screenshot_2022-05-06-07-55-41-704_it owlgram android](https://user-images.githubusercontent.com/91373907/167069613-fa8cc1ed-1559-4db4-8523-1cc365284618.jpg)

Get link work but download not work bot down

**Comment by fertkir** [comment]
Because when you click Download, the bot saves .torrent file to a directory on the server. This is because it was intended for deployment on your home servers.

Do you want it to send .torrent file in reply message?

**Comment by kamileecher** [comment]
yes, download the torrent to any directory, then send it to telegram as a message

**Comment by fertkir** [comment]
Okay, I'll do it

**Comment by kamileecher** [comment]
thank yo sir

**Comment by fertkir** [comment]
check it now

**Comment by kamileecher** [comment]
![Screenshot_2022-05-07-00-54-12-970_it owlgram android](https://user-images.githubusercontent.com/91373907/167221259-18309fbf-50b0-452d-bb89-e72e28ec30f4.jpg)
its work thank you sir😊

**Comment by fertkir** [comment]
You're welcome
